### ISSUE TITLE
error with oebb profile

### ISSUE THREAD

**Issue by CuzImMartin** [public-transport/hafas-client#318] opened 2024-07-13 21:29 UTC
Hi, I have been working on a project and have already worked with the db hafas client without any problems. now I wanted to query data from the öbb client as well. However, this error occurs when querying departures and arrivals:

```
Error fetching data from HAFAS: HafasError: ERROR: HCI Core: Error occurs : HCI Core: An ENUM value was used that is not available in the requested version/extension : root.svcResL.svcResL.res.common.rtSrcL.rtSrcL.type.type
    at checkIfResponseIsOk (file:///D:/Development/Projekte/xxx/hafas-api/node_modules/hafas-client/lib/request.js:103:9)
    at Object.request (file:///D:/Development/Projekte/xxx/hafas-api/node_modules/hafas-client/lib/request.js:206:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _stationBoard (file:///D:/Development/Projekte/xxx/hafas-api/node_modules/hafas-client/index.js:91:25)
    at async Object.departures (file:///D:/Development/Projekte/xxx/hafas-api/node_modules/hafas-client/index.js:109:10)
    at async file:///D:/Development/Projekte/xxx/hafas-api/server.mjs:66:34 {
  isHafasError: true,
  code: null,
  isCausedByServer: false,
  hafasCode: 'ERROR',
  request: Request {
    size: 0,
    timeout: 0,
    follow: 20,
    compress: true,
    counter: 0,
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 2,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    [Symbol(Body internals)]: {
      body: <Buffer 7b 22 6c 61 6e 67 22 3a 22 64 65 22 2c 22 73 76 63 52 65 71 4c 22 3a 5b 7b 22 6d 65 74 68 22 3a 22 53 74 61 74 69 6f 6e 42 6f 61 72 64 22 2c 22 72 65 ... 315 more bytes>,
      disturbed: false,
      error: null
    },
    [Symbol(Request internals)]: {
      method: 'POST',
      redirect: 'follow',
      headers: [Headers],
      parsedURL: [Url],
      signal: null
    }
  },
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://fahrplan.oebb.at/bin/mgate.exe?',
      status: 200,
      statusText: 'OK',
      headers: [Headers],
      counter: 0
    }
  },
  url: 'https://fahrplan.oebb.at/bin/mgate.exe?',
  hafasResponseId: 'd446bjkugkaqg4wg',
  hafasMessage: 'HCI Core: Error occurs : HCI Core: An ENUM value was used that is not available in the requested version/extension : root.svcResL.svcResL.res.common.rtSrcL.rtSrcL.type.type'
}
```

**Comment by derhuerst** [comment] 2024-07-15 17:18
Can you provide the request(s) that caused this error, as well as your `hafas-client` version?

**Comment by CuzImMartin** [comment] 2024-07-15 17:22
newest version of hafas-client and the departure request, i've not tryed others yet after i struggled a few hours with it

**Comment by derhuerst** [comment] 2024-07-15 17:26
> the departure request, i've not tryed others yet

With which stop/station ID?

**Comment by CuzImMartin** [comment] 2024-07-15 17:30
> Currently, I can't reproduce this problem when fetching departures from `8100013` & `8100173`.
> 
> 
> 
> Can you provide the request(s) that caused this error, as well as your `hafas-client` version?


It's not only about this 2 dep. I get the error all the time, i don't know if i'm dump and do something wrong, but for me nothing is working with the departure call. 

Maybe you provide a simple example what is working for you?

**Comment by derhuerst** [comment] 2024-07-15 17:34
Just like with https://github.com/public-transport/hafas-client/issues/233, this error seems to be not reproducible reliably.

**Comment by CuzImMartin** [comment] 2024-07-15 17:39
> > the departure request, i've not tryed others yet
> 
> 
> 
> With which stop/station ID?

Vienna mainstation with 8103000
and various other in austria, like Linz, Wels and Salzburg

**Comment by derhuerst** [comment] 2024-07-15 17:46
> Vienna mainstation with `8103000` […]

Still can't reproduce the problem.

**Comment by CuzImMartin** [comment] 2024-07-15 17:56
> > Vienna mainstation with `8103000` […]
> 
> 
> 
> Still can't reproduce the problem.

hafas-client with db-profile has the same stationIDs like oebb, right?

**Comment by derhuerst** [comment] 2024-07-15 18:01
> hafas-client with db-profile has the same stationIDs like oebb, right?

The station IDs are dictated by the HAFAS instance/endpoint. DB and ÖBB run different instances, but they might use the same IDs for some (many?) stations.

**Comment by CuzImMartin** [comment] 2024-07-15 18:18
i'm gonna try again in 3 hours, maybe i am lucky and get it work

**Comment by CuzImMartin** [comment] 2024-07-15 23:32
i got it to work, thank you very much

**Comment by derhuerst** [comment] 2024-07-16 11:22
> i got it to work, thank you very much

Please provide details on what you changed and how your determined if it works.

**Comment by CuzImMartin** [comment] 2024-07-16 11:50
> > i got it to work, thank you very much
> 
> 
> 
> Please provide details on what you changed and how your determined if it works.
> 
> 
> 
> Maybe we can resolve this for everyone who has this problem. And if we can't, we can try to further deduce under which circumstances the problem appears.

I used the same logic as for the db-profile, followed the cli and after a bit of trial and error it worked

**Comment by derhuerst** [comment] 2024-07-16 15:22
can you provide commands?

**Comment by derhuerst** [comment] 2024-08-08 13:47
Closing in favour of #233. Please post (new!) insights about the problem over there.

**Closed by derhuerst** 2024-08-08 13:47 UTC
Labels: bug, profile:oebb, upstream
