### ISSUE TITLE
SBB endpoint seems to be shut off

### ISSUE THREAD

**Issue by gaudes** [public-transport/hafas-client#245] opened 2021-08-22 11:35 UTC
Hi Janis,

once more I have an issue with SBB profile.

User reports that station search is not working.

I use the locations function. Here some details about the reported error:

```
Error.message | invalid response content-type: text/html; charset=UTF-8
Error.response | {size: 0, timeout: 0}
Error.stack | Error: invalid response content-type: text/html; charset=UTF-8     at /opt/iobroker/node_modules/hafas-client/lib/request.js:127:17     at processTicksAndRejections (internal/process/task_queues.js:95:5)     at fHelpers.getStation (/opt/iobroker/node_modules/iobroker.fahrplan/lib/helper.js:134:20)     at Fahrplan.onMessage (/opt/iobroker/node_modules/iobroker.fahrplan/main.js:94:28)
```

Searched station is "bassersdorf"

Thanks and regards,

Ralf

**Comment by derhuerst** [comment] 2021-08-22 11:41
Can you reproduce the error?

**Comment by gaudes** [comment] 2021-08-22 11:50
Currently not.

Problem occured 115 times at 5-6 users the last 30 days.

In Sentry I've seen that it occured also with DB profile.

**Comment by gaudes** [comment] 2021-08-22 11:53
I've just asked the issue creator if problem is temporary or permanently fails on his computer.

**Comment by derhuerst** [comment] 2021-08-23 11:07
I assume that this is due to some internal backend error that causes HAFAS's HTTP proxy to generate an HTML error page. It would really fit a pattern, as they disobey most HTTP API best practices.

**Comment by derhuerst** [comment] 2021-08-24 17:13
Unfortunately, it seems like the SBB endpoint is shut off. See also https://github.com/schildbach/public-transport-enabler/issues/381 .

**Comment by derhuerst** [comment] 2021-09-30 20:14
I'm going to close this Issue. Please re-open if you come across an SBB HAFAS endpoint.

**Closed by derhuerst** 2021-09-30 20:14 UTC
Labels: bug
