### ISSUE TITLE
HAFAS answers often with "ECONNRESET"

### ISSUE THREAD

**Issue by VanDerLars** [public-transport/hafas-client#293] opened 2023-06-23 07:14 UTC
Since some days we see the following behavior:

We make a call over Hafas Client and we get the following error message instead of the result:
`{"error":{"message":"request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=660a896737929f3e112c5e5679151ba7 failed, reason: read ECONNRESET","type":"system","errno":"ECONNRESET","code":"ECONNRESET"}}`

When we retry the exact same call one or two times, then the result comes often.

Also we monitor the Hafas Endpoint of Deutsche Bahn (reiseauskunft.bahn.de) with updown.io. The availability constantly got worse over the last weeks.
<img width="1025" alt="CleanShot 2023-06-23 at 09 12 31@2x" src="https://github.com/public-transport/hafas-client/assets/9517567/625aa5c9-3c76-4667-8332-318caace9d9f">

What could be the reason?

Do you know a way how to avoid the ECONNRESET error?

**Comment by derhuerst** [comment] 2023-06-23 08:42
`ECONNRESET` is the error code that Node.js returns if the TCP has been closed unexpectedly, usually either due to a lossy connection or due to a firewall closing it or dropping packets.

It might be that they're rate-limiting requests from your servers' IP addresses. I've observed similar behaviour with my servers.

I would suggest
- checking how many requests you're actually sending to them.
- investigating if this error appears with specific requests (e.g. specific HAFAS methods or specific stop IDs) only, in oder to rule out other possible causes.
- implementing a caching mechanism. – You could use [`cached-hafas-client`](https://npmjs.com/package/cached-hafas-client), but it has rather conservative default TTLs, so consider tweaking them.
- possibly requesting from more IP addresses.

> Also we monitor the Hafas Endpoint of Deutsche Bahn (reiseauskunft.bahn.de) with updown.io. The availability constantly got worse over the last weeks.

Do you monitor their endpoint directly, or do you monitor your API which pings their endpoint?

**Comment by Issam-Jendoubi** [comment] 2023-06-23 12:17
> Do you monitor their endpoint directly, or do you monitor your API which pings their endpoint?

We monitor their endpoint directly.

Actually, we were able to reproduce the issue locally. So, it seems that even if they have rate-limiting, it is not IP-based.

**Comment by derhuerst** [comment] 2023-06-23 12:24
> Actually, we were able to reproduce the issue locally. So, it seems that even if they have rate-limiting, it is not IP-based.

I'm not entirely sure about this. I've definitely run into IP-based rate limits even while developing locally, albeit with many requests. There might also be *multiple* limits in place, based on multiple factors.

**Comment by derhuerst** [comment] 2023-06-23 12:26
I'll close this Issue, given that I don't have control over how HaCon and/or DB run the HAFAS endpoint.

You're very welcome to post more findings about the `ECONNRESET` errors though!

**Closed by derhuerst** 2023-06-23 12:26 UTC
Labels: question, profile:db

**Comment by VanDerLars** [comment] 2023-07-10 08:15
what we see:
- `ECONRESET` seemingly happens randomly
- exact same request sometimes work, sometimes not
- no matter if we run it locally or in production, so there's no IP blocking
- there might be an algorithm when `ECONRESET` happens, but we see no pattern
- we "solved" by just retrying the same calls. the second, least the third attempt mostly work
