### ISSUE TITLE
"PARSE" Error when using with react-native

### ISSUE THREAD

**Issue by guitar9** [public-transport/hafas-client#56] opened 2018-05-28 22:49 UTC
Hi i get following error when i use it with react native. This is only with client.journys(..).  client.locations(..)  works fine.

This error is only when i am not in dubugging mode. When i am in debugging mode it works.
This is my code:

```
const createClient = require('hafas-client')
const dbProfile = require('hafas-client/p/db')
const client = createClient(dbProfile)
const münchenHbf = {
  type: 'station',
  id: '008000261',
  name: 'München Hbf',
  locations: {
    type: 'location',
    latitude:48.140364,
    longitude:11.558735
  }
}

const münchenPassing = {
  type: 'station',
  id: '008004158',
  name: 'München-Pasing',
  locations: {
    type: 'location',
    latitude:48.150036,
    longitude:11.461624
  }
}
const opt = {
  //var date2 = new Date('2018-12-17T03:24:00');
	when: new Date('2018-05-29T06:40:00'),
	whenRepresents: 'departure', // use 'arrival' for journeys arriving before `when`
	//earlierThan: null, // ref to get journeys earlier than the last query
	//laterThan: null, // ref to get journeys later than the last query
	results: 5, // how many journeys?
	via: null, // let journeys pass this station
	passedStations: false, // return stations on the way?
	transfers: 5, // maximum of 5 transfers
	transferTime: 0, // minimum time for a single transfer in minutes
	accessibility: 'none', // 'none', 'partial' or 'complete'
	bike: false, // only bike-friendly journeys
	products: {
		// these entries may vary from profile to profile
		suburban: true,
		subway: true,
		tram: true,
		bus: true,
		ferry: true,
		//express: true,
		regional: true
	},
	tickets: false, // return tickets? only available with some profiles
	polylines: false // return a shape for each leg?
}
    client.journeys(münchenPassing, münchenHbf, opt)
    .then((arr)=>{
      console.log('===============arr=====================');
      console.log(arr);
      console.log('====================================');

    })
    .catch(console.error)


  }
```

```
PARSE
request
    request.js:54:13
more
    index.js:134:18
journeys
    index.js:168:14
componentDidMount
    App.js:130:20
proxiedComponentDidMount
    createPrototypeProxy.js:61:45
commitLifeCycles
    ReactNativeRenderer-dev.js:10627:12
commitAllLifeCycles
    ReactNativeRenderer-dev.js:12512:10
invokeGuardedCallback
    ReactNativeRenderer-dev.js:39:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:221:34
commitRoot
    ReactNativeRenderer-dev.js:12677:10
completeRoot
    ReactNativeRenderer-dev.js:13685:46
performWorkOnRoot
    ReactNativeRenderer-dev.js:13635:23
performWork
    ReactNativeRenderer-dev.js:13545:26
performSyncWork
    ReactNativeRenderer-dev.js:13506:16
requestWork
    ReactNativeRenderer-dev.js:13392:6
scheduleWorkImpl
    ReactNativeRenderer-dev.js:13259:24
scheduleWork
    ReactNativeRenderer-dev.js:13207:28
scheduleRootUpdate
    ReactNativeRenderer-dev.js:13930:17
_updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:13966:6
updateContainer
    ReactNativeRenderer-dev.js:13991:8
render
    ReactNativeRenderer-dev.js:14726:35
renderApplication
    renderApplication.js:49:21
run
    AppRegistry.js:102:10
runApplication
    AppRegistry.js:194:26
__callFunction
    MessageQueue.js:351:47
<unknown>
    MessageQueue.js:116:26
__guardSafe
    MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    MessageQueue.js:115:17

```

**Comment by derhuerst** [comment] 2018-05-29 08:28
Which version of `hafas-client` do you use?

**Comment by derhuerst** [comment] 2018-05-30 12:11
cannot reproduce.

**Comment by guitar9** [comment] 2018-05-31 14:27
i am using react native and the version is 2.8.0 but i made some changes. import buffer, import random-bytes, ...

https://github.com/guitar9/hafas-client

Now i get the Error JSON Parse error: Unrecongnized token '?'

if I change 

'Accept-Encoding': 'gzip, deflate',

to 

'Accept': 'application/json',

i get the error PARSE

**Comment by guitar9** [comment] 2018-05-31 20:49
in request .js
![image](https://user-images.githubusercontent.com/25721108/40807540-e018de64-6524-11e8-9370-9fcc2727085e.png)



![image](https://user-images.githubusercontent.com/25721108/40807515-cbd594a6-6524-11e8-8b0f-77bc1e47b325.png)

**Comment by guitar9** [comment] 2018-05-31 20:59
the weird thing is when i change 
'Accept-Encoding': 'gzip, deflate'
to
'Accept-Encoding': 'application/json'
it goes, But only in debug Mode. In normal mode i get error "PARSE"

**Comment by guitar9** [comment] 2018-05-31 23:28
if I commend out the error part i get error "undefined is not a object (evaluating 'b.svcResL[0].res)"

```
		.then((b) => {
			console.log('=============here is error=======================');
			console.log(b);
			console.log('====================================');
			// if (b.err) {
			// 	err.message = b.err
			// 	throw err
			// }
			// if (!b.svcResL || !b.svcResL[0]) {
			// 	err.message = 'invalid response'
			// 	throw err
			// }
			// if (b.svcResL[0].err !== 'OK') {
			// 	err.message = b.svcResL[0].errTxt || b.svcResL[0].err
			// 	throw err
			// }
			const d = b.svcResL[0].res
			const c = d.common || {}

			if (Array.isArray(c.remL)) {
				d.remarks = c.remL.map(rem => profile.parseRemark(profile, rem))
			}
			if (Array.isArray(c.opL)) {
				d.operators = c.opL.map(op => profile.parseOperator(profile, op))
			}
			if (Array.isArray(c.prodL)) {
				const parse = profile.parseLine(profile, d.operators)
				d.lines = c.prodL.map(parse)
			}
			if (Array.isArray(c.locL)) {
				const parse = loc => profile.parseLocation(profile, loc, d.lines)
				d.locations = c.locL.map(parse)
			}
			return d
		})
```

**Comment by derhuerst** [comment] 2018-06-01 09:12
> i am using react native and the version is `2.8.0` but i made some changes. `import buffer`, `import random-bytes`, ...
>
> https://github.com/guitar9/hafas-client

I am willing to make `hafas-client` work in react-native without any modifications. I will create a branch for you to try.

**Comment by guitar9** [comment] 2018-06-01 09:26
okay thank you :)

Jannis Redmann <notifications@github.com> schrieb am Fr., 1. Juni 2018,
11:12:

**Comment by derhuerst** [comment] 2018-06-01 10:14
In [the `react-native-browser` branch](https://github.com/public-transport/hafas-client/tree/react-native-browser), I've included [ponyfills](https://ponyfill.com/) for `Buffer` and `Symbol`.

Will look into the HTTP headers thing.

**Comment by guitar9** [comment] 2018-06-01 14:38
get now error: 
`Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :react-native-randombytes`

**Comment by derhuerst** [comment] 2018-06-01 16:23
What about now? I pushed c78f64d.

**Comment by guitar9** [comment] 2018-06-01 16:43
I deleted the folder hafas-client and installed it again with

npm install git://github.com:public-transport/hafas-client.git#react-native-browser --save


how ever now i get error cant find variable Buffer.

```
Can't find variable: Buffer
<unknown>
    util.js:103:26
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    _stream_readable.js:46:11
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    readable.js:2:27
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:28:18
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:3:16
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:3:15
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    browser.js:3:10
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    request.js:3:19
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:11:17
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    App.js:99:21
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:2
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:141:45
_require
    require.js:132:20
global code
    
```

**Comment by guitar9** [comment] 2018-06-03 20:33
tried to change .json() to .text()

this is my response:
 request.js 71
```
��mS�8ǿJ��K~f��S�5$L�^ۻaŖ�űs�C�+|�{w_�v%;qB�kzm�^��diW�]�	>*�<Ur@LeO��*��A��0h�X|�~�)��Ez�M��gNB�1����A�~T���Х�
'iE(�2����)٭��YG9��2��54�p�r�z�8�4-G�<�G�$�R�xr`$fqrD�{G/��+x��=r,��y���PMK�=~}d���j*1��j>��\(�l�����ʡ*�p�>��(0�qS��8��SfʡtD�=�O1����k�"t3�J�0ޝeX�(�h3�~oYM{�������Q
t�hU�J��^�����ôub:�����pVut&���*c��vr?J2�]��Q6x���(JTm����Q�&V2�kԦ�Bp�X�f��_@%M|�����5��Ɠ�P줲A��{h�&���i�S��Z;##�{�B���Xޛ�����~=���0?(��$����~�fW<�Q�y�,�e�Ӹ:�!�,�c�(�w]�>�=�uy�֪Vk3�֒VkI��Zak/k�
��un�bd��JՕ5,>Y��N�ȶ啪ƪVc3�ƒVc�"��h���(�&�%��,�Y�/�Zi	c�O�`�I#Α�%�[Y�Y�BX4�����V���R>��'(^*oc8�ij��(
&1ͻ
��ZԆ�7�"�ռ$��3�עp��W���.�QCq'
.Y���Ł�I/F@�����0���	�G�	�-��<�ƾ�qb9*�*�U�:�2�U	�C���o�d3q�>t9Kj�v��N�)N�Fjgl�W�j=//_ב5��m�<����hh�f4ZN���T��Fw>�4������x��Nc�v�N8����4���~�A�!܄.�S�2<�v	��vq�1�Es�lnآ�0����j ���{/�=����'f�[Z{�t�U	���|���{� �5�Щߩw�zGX��*�?IB?LbC�M@l������0*����>���v=.�P�x�z^w���>�p.*�����Kv�c)��֙�R����S�.��Ι]�KH�esй�(�l2�<ܖm��o*-O�����_]d�R��\JǊ,�<�p�А�얅F\����_;MF�i聽�EǶz�܈����c�_�xC�A4�E� dI�gy�WG
Ǹ	pn$�N>���N�,ڠ��- 2���c�׬P���uKvwl�3���e��N�'���|,m���(:������[��yq����#����[e�q��l�p��n2��o��3J�%�/�N��;�_�=�	��6�}+u����=w�Mp�pV*�V��������p_�{�d�"���l�{C]�V�N��?�鍯�t�\���~�u��U�����<�t�ML�pV*Fq�U����I���e�ϗ�a:�f�A�V��=�t�o��O9���
�iãٮ/?����Vhm��T��ƍ��2�p����V�|w]%�1�k�w�]�����ט����K�+.�q�j���]�<��Y���u��_|6e7\:��`�l��S�:v���[�"vc8+�����J���Uv�ߒ�ΐ[�o�}!�e�O]/�����wg�Bv�n��<�ʇ
?�4�K��!;��74"^�л����-���R�7�O�6����i�A�T������;���C#V�@�5����`\�9�,z��*��A����+��08�ee�8�g��o9��;��_�jD�'
```

**Comment by guitar9** [comment] 2018-06-03 20:51
this what i getting as response when i am not in debug mode:
{"ver":"1.16","ext":"DB.R15.12.a","lang":"eng","id":"","err":"PARSE","svcResL":[]}

**Comment by guitar9** [comment] 2018-06-03 21:16
I have different bodys in debug mode and in production mode. 
Out date and Out Time is: Invalid Date in production mode and the checksum is in production mode and debug mode not the same.

I have uploaded a comparssion between the two bodys. 

[DiffNow Comparison Report (1).htm.zip](https://github.com/public-transport/hafas-client/files/2066367/DiffNow.Comparison.Report.1.htm.zip)

**Comment by derhuerst** [comment] 2018-06-04 08:28
> I have different bodys in debug mode and in production mode.

Which debug and production mode are you referring to?

> Out date and Out Time is: `Invalid Date` in production mode [...].

This is very weird. Will try to figure out why.

In the meanwhile, can you try to, *instead* of the `react-native-browser` branch, just use `hafas-client@next` and [`node-libs-react-native`](https://github.com/parshap/node-libs-react-native#usage)?

**Comment by guitar9** [comment] 2018-06-04 16:00
> Which debug and production mode are you referring to?

If I run my app on a device I can open dev menu and start debugger mode on device. 
At http://localhost:8081/debugger-ui/ I see then what i have logged out.

**Comment by guitar9** [comment] 2018-06-07 00:06
tried to install hafas-client@next and node-libs-react-native.
I had to install es6-symbol and require it in loyalty-cards and comment out 			
"//'Accept-Encoding': 'gzip, deflate'" in request.js

Than i have the same problem like before. In debug mode everything is fine but in normal mode the checksum and the Out date and Out time are not correct

**Comment by guitar9** [comment] 2018-06-07 00:33
Here is my Example Project

[https://www.file-upload.net/download-13176288/hafas-client-react-native.zip.html](url)

**Comment by guitar9** [comment] 2018-06-07 09:52
or at github
[React Native Hafas Client example Repo](https://github.com/guitar9/hafas-client-example)

**Comment by guitar9** [comment] 2018-06-11 19:12
have updated it.

now get error from create hash:

```
The development server returned response error code: 500

URL: http://localhost:8081/index.delta?platform=android&dev=true&minify=false&deltaBundleId=af226ea22bdc3186

Body:
{"originModulePath":"/home/t/ws/react/hafas-client-example/example/node_modules/cipher-base/index.js","targetModuleName":"stream","message":"Unable to resolve module `stream` from `/home/t/ws/react/hafas-client-example/example/node_modules/cipher-base/index.js`: Module `stream` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `stream` from `/home/t/ws/react/hafas-client-example/example/node_modules/cipher-base/index.js`: Module `stream` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `stream` from `/home/t/ws/react/hafas-client-example/example/node_modules/cipher-base/index.js`: Module `stream` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (/home/t/ws/react/hafas-client-example/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:1460)\n    at ResolutionRequest.resolveDependency (/home/t/ws/react/hafas-client-example/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)\n    at DependencyGraph.resolveDependency (/home/t/ws/react/hafas-client-example/example/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)\n    at dependencies.map.relativePath (/home/t/ws/react/hafas-client-example/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)\n    at Array.map (native)\n    at resolveDependencies (/home/t/ws/react/hafas-client-example/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)\n    at /home/t/ws/react/hafas-client-example/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33\n    at Generator.next (<anonymous>)\n    at step (/home/t/ws/react/hafas-client-example/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)\n    at /home/t/ws/react/hafas-client-example/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473"}
processBundleResult
    BundleDownloader.java:266
access$200
    BundleDownloader.java:35
onResponse
    BundleDownloader.java:153
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764

```

**Comment by derhuerst** [comment] 2018-06-11 19:23
>> I forgot that `node-libs-react-native` only fixes Node-builtin *modules* for react-native, but not Node-builtin *globals*. So my `hafas-client@next` + `node-libs-react-native` proposal did't make sense.
>
> Unable to resolve module `stream` from `/home/t/ws/react/hafas-client-example/example/node_modules/cipher-base/index.js`: Module `stream` does not exist in the Haste module map

Did you use `node-libs-react-native`? Please do this.

**Comment by guitar9** [comment] 2018-06-11 20:22
ok i have added it. Now i get Unrecognized token '?'. If i now comment out 'Accept-Encoding': 'gzip, deflate'  i get that special case that it works in debug mode but in normal mode not.

**Comment by derhuerst** [comment] 2018-06-12 08:19
Can you log the response by and send it? The appropriate place would be here: https://github.com/public-transport/hafas-client/blob/c78f64d12a4e4b1b835731b39dd90030b4d5117d/lib/request.js#L67

You can log the response like this:

```js
	return fetch(url, req)
	.then((res) => {
		err.statusCode = res.status
		if (!res.ok) {
			err.message = res.statusText
			throw err
		}
		return res.text()
	})
	.then((raw) => {
		console.error(raw)
		return JSON.parse(raw)
	})
	.then((b) => {
```

**Comment by guitar9** [comment] 2018-06-12 09:07
Request:
`{"method":"post","body":"{\"lang\":\"en\",\"svcReqL\":[{\"cfg\":{\"polyEnc\":\"GPA\"},\"meth\":\"TripSearch\",\"req\":{\"outDate\":\"Invalid DateTime\",\"outTime\":\"Invalid DateTime\",\"ctxScr\":null,\"getPasslist\":false,\"maxChg\":5,\"minChgTime\":0,\"depLocL\":[{\"lid\":\"A=1@L=008000261@\"}],\"viaLocL\":null,\"arrLocL\":[{\"lid\":\"A=1@L=008004158@\"}],\"jnyFltrL\":[{\"type\":\"PROD\",\"mode\":\"INC\",\"value\":\"1023\"},{\"type\":\"META\",\"mode\":\"INC\",\"meta\":\"notBarrierfree\"}],\"getTariff\":false,\"outFrwd\":true,\"getPT\":true,\"getIV\":false,\"getPolyline\":false,\"numF\":5,\"trfReq\":{\"jnyCl\":2,\"tvlrProf\":[{\"type\":\"E\",\"redtnCard\":null}],\"cType\":\"PK\"}}}],\"client\":{\"id\":\"DB\",\"v\":\"16040000\",\"type\":\"IPH\",\"name\":\"DB Navigator\"},\"ext\":\"DB.R15.12.a\",\"ver\":\"1.16\",\"auth\":{\"type\":\"AID\",\"aid\":\"n91dB8Z77MLdoR0K\"}}","headers":{"Content-Type":"application/json","Accept-Encoding":"gzip, deflate","Accept":"application/json","user-agent":"https://github.com/public-transport/hafas-client"},"query":{"checksum":"0d8186da7b06f9cc094075a2a6e21b00"}}`

Response:
`�`

Error:
JSON Parse Error: Unrecongnized token "?"

**Comment by derhuerst** [comment] 2018-06-13 13:42
This is with `Accept-Encoding: gzip`?

**Comment by guitar9** [comment] 2018-06-13 15:13
with Accept-Encoding': 'gzip, deflate',

**Comment by guitar9** [comment] 2018-06-24 19:39
problem was package luxon. After exams in a few weeks I will get it done.

**Comment by derhuerst** [comment] 2018-06-25 11:08
I've had a look into this once more.

**I successfully ran `hafas-client@3.0.0-alpha.9` – installed via `npm i hafas-client@next` – on the device and managed to fetch departures.** I [added `node-libs-react-native` to the config](https://github.com/parshap/node-libs-react-native/tree/89d7366edb19223e1a86a70e2961ffdb546d8b18#usage-with-react-native-packager) and [used the global shims](https://github.com/parshap/node-libs-react-native/tree/89d7366edb19223e1a86a70e2961ffdb546d8b18#globals). Will add a notice about this to the readme.

I assume all other errors are related to specifics of your local setup. I'm willing to help debug this, but only with comprehensive info.

**Comment by derhuerst** [comment] 2018-06-25 11:13
I will close this. Please reopen with more details if you still have issues.

**Closed by derhuerst** 2018-06-25 11:13 UTC
Labels: bug

**Comment by soldatos** [comment] 2022-11-19 13:49
Hello @derhuerst 
i am really desperate. Do you have a branch for react-native version? I can't get node-libs-react-native to integrate.
Thank you

**Comment by bergmannjg** [comment] 2022-11-19 14:37
Hi @soldatos,

please have a look at [FahrplanApp](https://github.com/bergmannjg/FahrplanApp) for an example of hafas-client with react native.

**Comment by derhuerst** [comment] 2022-11-19 15:33
I can't provide a known-working version, sorry; react-native is not a priority for me, and setting it up is just too much of a hassle. I have googled a bit™ though:

As of version `6.0.0`, `hafas-client` makes use of the following dependencies (this is similar with `hafas-client@5`) that are *not* self-contained environment-independent JS:

- [`create-hash@1.2.0`](https://github.com/crypto-browserify/createHash/tree/v1.2.0) – [in the browser, it uses pure JS implementations of the hash algorithms](https://github.com/crypto-browserify/createHash/blob/v1.2.0/browser.js), not sure what it does in react-native, but [there is an Issue about it](https://github.com/crypto-browserify/createHash/issues/26)
- [`cross-fetch@3.1.5`](https://github.com/lquixada/cross-fetch/tree/v3.1.5) - [it seems to just work™ in react-native](https://github.com/lquixada/cross-fetch/blob/24dedb4c8a16a33cb9b4d4682fb731438a6a9e2d/examples/reactnative/components/pony-page.js#L3)
- [`https-proxy-agent@5.0.1`](https://github.com/TooTallNate/node-https-proxy-agent/tree/5.0.1) – it makes use of several Node builtins, e.g. `net`, `tls` & `http`.

It also uses the following Node builtins:

- `assert` – should be easy to mock
- `crypto`
- `fs` – used in `p/{kvb,sncb,ivb}/index.js` in order to load SSL certificates, so if you don't use those profiles, you should be fine
- `https`
- `module` – not sure how to polyfill it
- `net` – not sure how to polyfill it, but only `isIP` is being used from it
- `util` – should be easy to mock
- `zlib` – not sure how to polyfill it

**Comment by derhuerst** [comment] 2022-11-19 15:34
> […] have a look at [FahrplanApp](https://github.com/bergmannjg/FahrplanApp) for an example of hafas-client with react native.

Specifically, the shims/polyfills are defined here: https://github.com/bergmannjg/FahrplanApp/blob/a11b4272ff4623f7d015b1491ad5c2297d180dfa/metro.config.js#L24
