### ISSUE TITLE
Journeys on DB seem to return -0.01€ price after 2024-12-15

### ISSUE THREAD

**Issue by Krystex** [public-transport/hafas-client#333] opened 2024-12-09 19:53 UTC
I don't know if I'm making a mistake, but journeys after the 2024-12-15 seem to return the ticket price of -0.01€.

```js
const res = await client.journeys('8000261', '8000105', {
    departure: "2024-12-15T15:00:00+01:00",
    results: 5,
    transfers: 0
})
```
Output:
```
2024-12-15T15:50:00+01:00 ICE 620   -0.01
2024-12-15T16:18:00+01:00 ICE 1222   -0.01
2024-12-15T16:48:00+01:00 ICE 528   -0.01
2024-12-15T17:51:00+01:00 ICE 526   -0.01
2024-12-15T18:47:00+01:00 ICE 524   -0.01
```

I tried multiple origins and destination, all return the same value.

**Comment by traines-source** [comment] 2024-12-09 20:57
duplicate of https://github.com/public-transport/hafas-client/issues/331, see there :)

**Closed by traines-source** 2024-12-09 20:57 UTC
